%% Copyright 2014 MERCIER David
function gui_handle = demo
%% Function to run the Matlab GUI for the analysis of the pop-in statistics
% through Weibull or Gauss distributions
%% Initialization
clear all; close all; clear classes;
delete(findall(0,'Type','figure'));
format compact;
commandwindow; clc; clearvars;

gui = struct();
gui.config = struct();

%% Paths Management
path_management_GUI; %Definition of the Matlab search paths
if ismac || isunix
    addpath(genpath('path\to\codes'));
else
    addpath(genpath('path/to/codes'));
end

[startdir, f, ext] = fileparts(mfilename('fullpath'));
cd(startdir);

%% Set Toolbox version and help paths
gui.config.POPINroot = get_popin_root; % ensure that environment is set
gui.config.name_toolbox = 'PopIn';
gui.config.version_toolbox = '2.3';
gui.config.url_help = 'http://popin.readthedocs.org/en/latest/';
gui.config.pdf_help = 'https://media.readthedocs.org/pdf/popin/latest/popin.pdf';

%% Main Window Coordinates Configuration
scrsize = get(0, 'ScreenSize'); % Get screen size
WX = 0.05 * scrsize(3);           % X Position (bottom)
WY = 0.10 * scrsize(4);           % Y Position (left)
WW = 0.90 * scrsize(3);           % Width
WH = 0.80 * scrsize(4);           % Height

%% Main Window Configuration
gui.handles.MainWindows = figure('Name', ...
    strcat(gui.config.name_toolbox, '_Version_', gui.config.version_toolbox),...
    'NumberTitle', 'off',...
    'PaperUnits', get(0, 'defaultfigurePaperUnits'),...
    'Color', [0.9 0.9 0.9],...
    'Colormap', get(0,'defaultfigureColormap'),...
    'toolBar', 'figure',...
    'InvertHardcopy', get(0, 'defaultfigureInvertHardcopy'),...
    'PaperPosition', [0 7 50 15],...
    'Position', [WX WY WW WH]);

%% Title of the GUI
gui.handles.title_GUI_1 = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.325 0.96 0.55 0.04],...
    'String', 'Analysis of the pop-in statistics through Weibull distribution',...
    'FontWeight', 'bold',...
    'FontSize', 12,...
    'HorizontalAlignment', 'center',...
    'ForegroundColor', 'red');

gui.handles.title_GUI_2 = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.325 0.93 0.55 0.03],...
    'String', ['Version ', gui.config.version_toolbox, ...
    ' - Copyright 2014 MERCIER David'],...
    'FontWeight', 'bold',...
    'FontSize', 10,...
    'HorizontalAlignment', 'center',...
    'ForegroundColor', 'red');

%% Date / Time
gui.handles.date_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'String', datestr(datenum(clock),'mmm.dd,yyyy HH:MM'),...
    'Position', [0.92 0.975 0.075 0.02]);

%% Buttons to browse in files
gui.handles.opendata_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.018 0.94 0.06 0.05],...
    'String', 'Select file',...
    'FontSize', 10,...
    'FontWeight','bold',...
    'BackgroundColor', [0.745 0.745 0.745],...
    'Callback', 'openfile');

gui.handles.opendata_str_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [0.018 0.90 0.3 0.04],...
    'String', pwd,...
    'FontSize', 8,...
    'BackgroundColor', [0.9 0.9 0.9]);

gui.handles.typedata_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.018 0.87 0.3 0.03],...
    'String', '.xls ==> 3 columns : Segments / Displacement / Load ',...
    'HorizontalAlignment', 'left');

%% Definition of the minimum/maximum depth
gui.handles.title_mindepth_prop_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.02 0.83 0.07 0.03],...
    'String', 'Minimum depth :',...
    'HorizontalAlignment', 'left',...
    'Visible', 'on');

gui.handles.value_mindepth_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [0.08 0.83 0.03 0.03],...
    'String', '',...
    'Visible', 'on');

gui.handles.unit_mindepth_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.11 0.83 0.02 0.03],...
    'String', 'nm',...
    'HorizontalAlignment', 'center',...
    'Visible', 'on');

gui.handles.title_maxdepth_prop_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.02 0.80 0.07 0.03],...
    'String', 'Maximum depth :',...
    'HorizontalAlignment', 'left',...
    'Visible', 'on');

gui.handles.value_maxdepth_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [0.08 0.80 0.03 0.03],...
    'String', '',...
    'Visible', 'on');

gui.handles.unit_maxdepth_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.11 0.80 0.02 0.03],...
    'String', 'nm',...
    'HorizontalAlignment', 'center',...
    'Visible', 'on');

%% Number of pop-in
gui.handles.title_num_popin_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.02 0.75 0.15 0.03],...
    'String', 'Which pop-in to analyze ?',...
    'HorizontalAlignment', 'left');

gui.handles.value_num_popin_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'popup',...
    'Position', [0.02 0.72 0.15 0.03],...
    'String', '1st pop-in|2nd pop-in',...
    'Value', 1);

%% Set the critical parameter
gui.handles.title_crit_param_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.02 0.68 0.15 0.03],...
    'String', 'Which critical parameter to analyze ?',...
    'HorizontalAlignment', 'left');

gui.handles.value_crit_param_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'popup',...
    'Position', [0.02 0.65 0.15 0.03],...
    'String', 'Load|Displacement',...
    'Value', 1);

%% Run calculation if new parameters set
gui.handles.run_calc_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.02 0.56 0.10 0.06],...
    'String', 'Run calculation...',...
    'FontSize', 12,...
    'BackgroundColor', [0.745 0.745 0.745],...
    'Callback', 'get_and_plot_set');

%% Parameters to plot on x and y axis
gui.handles.title_param2plotinxaxis_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.02 0.50 0.10 0.03],...
    'String', 'Parameter to plot ==> x axis',...
    'HorizontalAlignment', 'left');

gui.handles.value_param2plotinxaxis_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'popup',...
    'Position', [0.02 0.47 0.10 0.03],...
    'String', 'Displ.(h)|Load(L)|dh|ddh|dL|ddL',...
    'Value', 1,...
    'Callback', 'plot_load_disp_set');

gui.handles.title_param2plotinyaxis_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.02 0.43 0.10 0.03],...
    'String', 'Parameter to plot ==> y axis',...
    'HorizontalAlignment', 'left');

gui.handles.value_param2plotinyaxis_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'popup',...
    'Position', [0.02 0.40 0.10 0.03],...
    'String', 'Displ.(h)|Load(L)|dh|ddh|dL|ddL',...
    'Value', 2,...
    'Callback', 'plot_load_disp_set');

%% Options of the plot
gui.handles.cb_log_plot_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'checkbox',...
    'Position', [0.02 0.36 0.03 0.03],...
    'String', 'Log',...
    'Callback', 'plot_load_disp_set');

gui.handles.cb_grid_plot_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'checkbox',...
    'Position', [0.06 0.36 0.03 0.03],...
    'String', 'Grid',...
    'Callback', 'plot_load_disp_set');

%% Get values from plot
gui.handles.cb_get_values_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.02 0.32 0.10 0.03],...
    'String', 'Get values x and y values',...
    'Visible', 'on',...
    'Callback', 'plot_get_values');

gui.handles.title_x_values_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.02 0.29 0.03 0.03],...
    'String', 'X value :',...
    'HorizontalAlignment', 'left',...
    'Visible', 'on');

gui.handles.value_x_values_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [0.052 0.29 0.04 0.03],...
    'String', '',...
    'Visible', 'on');

gui.handles.title_y_values_prop_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.02 0.26 0.03 0.03],...
    'String', 'Y value :',...
    'HorizontalAlignment', 'left',...
    'Visible', 'on');

gui.handles.value_y_values_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [0.052 0.26 0.04 0.03],...
    'String', '',...
    'Visible', 'on');

%% Axis properties
positionVector1 = [0.25 0.06 0.325 0.75];
gui.handles.AxisPlot_GUI_1 = subplot('Position', positionVector1);

positionVector2 = [0.65 0.06 0.325 0.75];
gui.handles.AxisPlot_GUI_2 = subplot('Position', positionVector2);

%% Help
gui.handles.save_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.02 0.16 0.1 0.05],...
    'String', 'HELP',...
    'FontSize', 12,...
    'BackgroundColor', [0.745 0.745 0.745],...
    'Callback', 'gui = guidata(gcf); web(gui.config.url_help,''-browser'')');

%% Save
gui.handles.save_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.02 0.105 0.1 0.05],...
    'String', 'SAVE',...
    'FontSize', 12,...
    'BackgroundColor', [0.745 0.745 0.745],...
    'Callback', 'save_figures_set');

%% Quit
gui.handles.quit_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.02 0.05 0.1 0.05],...
    'String', 'QUIT',...
    'FontSize', 12,...
    'BackgroundColor', [0.745 0.745 0.745],...
    'Callback', 'finish_sav');

%% Help menu
customized_menu(gcf);

%% Set flags;
gui.flag.flag_data = 0;
gui.flag.flag_cleaned_data = 0;

%% Encapsulation of data into the GUI
guidata(gcf, gui);

gui_handle = ishandle(gcf);

end

function path_management_GUI(varargin)
%% Set Matlab search path
%
%TODO: checkout addpath_recurse which mtex uses
% http://www.mathworks.com/matlabcentral/fileexchange/21086-recursive-addpath/content/addpath_recurse.m
%
% http://www.mathworks.de/de/help/matlab/ref/addpath.html
commandwindow;
% http://stackoverflow.com/questions/2720140/find-location-of-current-m-file-in-matlab
S = dbstack('-completenames');
[folder, name, ext] = fileparts(S(1).file);

path_to_add = genpath(folder);

% Add path for 'util' folder to use 'cells_filter', 'cell2path' and
% 'path2cell' functions
util_path = fullfile(folder, 'util');
addpath(util_path);

path_cell = path2cell(path_to_add);
% Do not put version control metadata on the search path

if ispc
    psep = '\';
else
    psep = '/';
end
   
path_cell_filtered = cellstr_filter(path_cell, {[psep, '.git']});
%path_cell_filtered = cellstr_filter(path_cell, {[psep, '.']}); % all dot dirs?
%path_cell_filtered = path_cell; % no filter

n_dirs = numel(path_cell_filtered);
%n_filtered_entries = numel(path_cell) - n_dirs;

path_to_add = cell2path(path_cell_filtered);

fprintf('%s\n', folder)
if nargin > 0 && ischar(varargin{1})
    answer = varargin{1};
else
    display(['Add the above folder with subfolders ' ...
        'to the Matlab search path?'])
    fprintf('(%i items)\n', n_dirs)
    answer = input('([y](default)/n/rm(remove))','s');
end

root_var = 'POPIN_TBX_ROOT';
if strcmpi(answer, 'y') || isempty(answer)
    fprintf('Adding %i entries to the Matlab search path\n', n_dirs);
    addpath(path_to_add);
    %savepath;
    setenv(root_var, folder)
elseif strcmpi(answer, 'rm')
    fprintf('Removing %i entries from Matlab search path\n', n_dirs);
    rmpath(path_to_add);
    % delete environment variable, TODO: works on Linux?
    setenv(root_var, '') 
else
    display('doing nothing');
end

%% Optionally display the matlab search path after modifications with the 'path' command
%path
end

function path_cell_filtered = cellstr_filter(path_cell, extension2filter)

for ii = 1:length(path_cell)
    if strcmp(path_cell{ii}, extension2filter) == 1;
        path_cell{ii} = {''};
    end
end
path_cell_filtered = path_cell;
end

function path_list = cell2path(path_cell)

path_strcat = '';

for ii = 1:length(path_cell)
    path_strcat = strcat(path_strcat, ';', path_cell{ii});
end
path_list = path_strcat;
end
