# Copyright 2014 MERCIER David
# Be careful to put a comma + a space between each data...! (YAML convention)
###########################################################################################
# Constants used in the calculation of the cumulative function of Weibull (1951)
Min_mWeibull: 0
Max_mWeibull: 1000

###########################################################################################
# Constants used in the calculation of the cumulative function of 
# Chechenin et al. (1995) - DOI: 10.1016/S0040-6090(94)06494-6
Min_mChechenin: 0
Max_mChechenin: 1000

###########################################################################################
# Constants used in the calculation of the cumulative function of 
# Mason et al. (2006) - DOI: 10.1103/PhysRevB.73.054102
K: 3.14 #pi
eta_var: 7e25 #in s-1.m-3
epsilon_var: 0.34 #in eV
Vact: 10 #in Angstrom3
k_Boltzmann: 1.3806488e-23 #Boltzmann's constant in  m2.kg.s-2.K-1

###########################################################################################
# Options for the least square method of Matlab used to fit experimental curves
TolFun_value: 1e-20
TolX_value: 1e-20
MaxIter_value: 10000