%% Copyright 2014 MERCIER David
function weibull_cdf(OPTIONS, xdata_fit, ydata_fit)
%% Function giving the Weibull cumulative distribution function
% See http://de.mathworks.com/help/stats/wblcdf.html
% See Weibull W., “A statistical distribution function of wide applicability”, J. Appl. Mech.-Trans. ASME (1951), 18(3).

gui = guidata(gcf);

gui.cumulativeFunction.xdata_cdf = xdata_fit;

% Model (mortal function)
weibull_cdf_m = @(p,x) (1 - exp(-(x./p(2)).^p(1)));

% Make a starting guess of coefficients p(1) and p(2)
% p(1) = Weibull modulus --> 10 when good homogeneity in size defect distribution
% p(2) = Mean critical value
gui.cumulativeFunction.p0 = [1 ; mean(ydata_fit)];

[gui.cumulativeFunction.coefEsts, ...
    gui.cumulativeFunction.resnorm, ...
    gui.cumulativeFunction.residual, ...
    gui.cumulativeFunction.exitflag, ...
    gui.cumulativeFunction.output, ...
    gui.cumulativeFunction.lambda, ...
    gui.cumulativeFunction.jacobian] =...
    lsqcurvefit(weibull_cdf_m, gui.cumulativeFunction.p0, ...
    gui.cumulativeFunction.xdata_cdf, ydata_fit, ...
    [gui.config.numerics.Min_mWeibull ; 0], ...
    [gui.config.numerics.Max_mWeibull ; max(ydata_fit)], ...
    OPTIONS);

gui.cumulativeFunction.coefEsts(1) = ...
    real(gui.cumulativeFunction.coefEsts(1));
gui.cumulativeFunction.coefEsts(2) = ...
    real(gui.cumulativeFunction.coefEsts(2));

gui.cumulativeFunction.ydata_cdf = ...
    (1 - exp(-(gui.cumulativeFunction.xdata_cdf./gui.cumulativeFunction.coefEsts(2)) ...
    .^ gui.cumulativeFunction.coefEsts(1)));

guidata(gcf, gui);

end